<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Collager</AssemblyName>
    <RootNamespace>Collager</RootNamespace>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <RepositoryUrl>https://github.com/CasseShimada/Collager</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Installer\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\AppIcon.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
